apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: apibolsa-cache
  namespace: apibolsa
  labels:
    app.kubernetes.io/name: infinispan
    app.kubernetes.io/part-of: apibolsa
spec:
  replicas: 1
  service:
    type: DataGrid
  container:
    cpu: "500m"
    memory: "512Mi"
  logging:
    categories:
      org.infinispan: "info"
      org.jboss.as: "info"

