apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: apibolsa
  labels:
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: apibolsa
spec:
  selector:
    app.kubernetes.io/name: nodejs
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  type: ClusterIP



