apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: apibolsa
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: apibolsa
spec:
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  type: ClusterIP



