apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: apibolsa-kafka
  namespace: apibolsa
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: apibolsa
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      num.partitions: 3
    storage:
      type: ephemeral
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  entityOperator:
    topicOperator: {}
    userOperator: {}



